In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
date=pd.date_range('20180701',periods=4)

In [4]:
import time
import datetime
#datetime.datetime()

In [5]:
plt.style.use("ggplot")

In [6]:
datetime.date.today()
#plt.show()

datetime.date(2019, 6, 21)

In [9]:
index=pd.Series(datetime.date.today())

In [10]:
import pandas as pd
df=pd.read_csv("G://data/h-1b-visa/h1b_kaggle.csv")

In [11]:
df.shape

(3002458, 12)

In [12]:
df.size

36029496

In [13]:
df.ndim

2

In [15]:
import pandas as pd

In [16]:
df.head()

,Unnamed: 0,Unnamed: 0.1,Status,EMPLOYER_NAME,SOC_NAME,JOB_TITLE,FULL_TIME_POSITION,PREVAILING_WAGE,YEAR,WORKSITE,lon,lat
0,0,1,CERTIFIED-WITHDRAWN,UNIVERSITY OF MICHIGAN,BIOCHEMISTS AND BIOPHYSICISTS,POSTDOCTORAL RESEARCH FELLOW,N,36067.0,2016.0,"ANN ARBOR, MICHIGAN",-83.743038,42.280826
1,1,2,CERTIFIED-WITHDRAWN,"GOODMAN NETWORKS, INC.",CHIEF EXECUTIVES,CHIEF OPERATING OFFICER,Y,242674.0,2016.0,"PLANO, TEXAS",-96.698886,33.019843
2,2,3,CERTIFIED-WITHDRAWN,"PORTS AMERICA GROUP, INC.",CHIEF EXECUTIVES,CHIEF PROCESS OFFICER,Y,193066.0,2016.0,"JERSEY CITY, NEW JERSEY",-74.077642,40.728158
3,3,4,CERTIFIED-WITHDRAWN,"GATES CORPORATION, A WHOLLY-OWNED SUBSIDIARY O...",CHIEF EXECUTIVES,"REGIONAL PRESIDEN, AMERICAS",Y,220314.0,2016.0,"DENVER, COLORADO",-104.990251,39.739236
4,4,5,WITHDRAWN,PEABODY INVESTMENTS CORP.,CHIEF EXECUTIVES,PRESIDENT MONGOLIA AND INDIA,Y,157518.4,2016.0,"ST. LOUIS, MISSOURI",-90.199404,38.627003

In [20]:
df.rename({"Status":"status","EMPLOYER_NAME":"company","PREVAILING_WAGE":"salary","WORKSITE":"state"},axis=1,inplace=True)

In [21]:
df.head()

,Unnamed: 0,Unnamed: 0.1,status,company,SOC_NAME,JOB_TITLE,FULL_TIME_POSITION,salary,YEAR,state,lon,lat
0,0,1,CERTIFIED-WITHDRAWN,UNIVERSITY OF MICHIGAN,BIOCHEMISTS AND BIOPHYSICISTS,POSTDOCTORAL RESEARCH FELLOW,N,36067.0,2016.0,"ANN ARBOR, MICHIGAN",-83.743038,42.280826
1,1,2,CERTIFIED-WITHDRAWN,"GOODMAN NETWORKS, INC.",CHIEF EXECUTIVES,CHIEF OPERATING OFFICER,Y,242674.0,2016.0,"PLANO, TEXAS",-96.698886,33.019843
2,2,3,CERTIFIED-WITHDRAWN,"PORTS AMERICA GROUP, INC.",CHIEF EXECUTIVES,CHIEF PROCESS OFFICER,Y,193066.0,2016.0,"JERSEY CITY, NEW JERSEY",-74.077642,40.728158
3,3,4,CERTIFIED-WITHDRAWN,"GATES CORPORATION, A WHOLLY-OWNED SUBSIDIARY O...",CHIEF EXECUTIVES,"REGIONAL PRESIDEN, AMERICAS",Y,220314.0,2016.0,"DENVER, COLORADO",-104.990251,39.739236
4,4,5,WITHDRAWN,PEABODY INVESTMENTS CORP.,CHIEF EXECUTIVES,PRESIDENT MONGOLIA AND INDIA,Y,157518.4,2016.0,"ST. LOUIS, MISSOURI",-90.199404,38.627003

In [23]:
df["salary"].max()

6997606720.0

In [24]:
df["salary"].min()

0.0

In [29]:
s=df.groupby(["status"])["company"]

In [30]:
s

In [31]:
s=df.sort_values("salary",ascending=False)

In [32]:
s.head(25)

,Unnamed: 0,Unnamed: 0.1,status,company,SOC_NAME,JOB_TITLE,FULL_TIME_POSITION,salary,YEAR,state,lon,lat
2163248,2163248,2163249,DENIED,"GUARDIAN HEALTHCARE PROVIDERS, INC.",Physical Therapists,PHYSICAL THERAPISTS,Y,6.997607e+09,2013.0,"PEKIN, ILLINOIS",-89.640658,40.567539
2797982,2797982,2797983,DENIED,"SCIVANTAGE, INC.",Computer Programmers,SOFTWARE DEVELOPER,Y,1.007814e+09,2011.0,"JERSEY CITY, NEW JERSEY",-74.077642,40.728158
1673867,1673867,1673868,DENIED,DISCOVER PRODUCTS INC.,Statisticians,PROJECT MANAGER,Y,8.201323e+08,2014.0,"RIVERWOODS, ILLINOIS",-87.897014,42.167525
1819718,1819718,1819719,DENIED,"IDEXCEL, INC.","Software Developers, Applications",.NET DEVELOPER,Y,7.099999e+08,2013.0,"COLUMBUS, OHIO",-82.998794,39.961176
2775906,2775906,2775907,DENIED,COMMONHEALTH ACTION,Medical and Health Services Managers,PROGRAM MANAGER (POSITIVE PATHWAYS),Y,6.579000e+08,2011.0,"WASHINGTON, NA",NaN,NaN
1547574,1547574,1547575,DENIED,ARKRIT LLC,Computer Systems Analysts,PROGRAMMER/ANALYST,Y,6.169317e+08,2014.0,"SAN JOSE, CALIFORNIA",-121.886329,37.338208
1668384,1668384,1668385,DENIED,HOWARD HUGHES MEDICAL INSTITUTE,"Life Scientists, All Other",RESEARCH ASSOCIATE,Y,4.134726e+08,2014.0,"ASHBURN, VIRGINIA",-77.487442,39.043757
1805875,1805875,1805876,DENIED,GOOGLE INC.,Architectural and Engineering Managers,"MANAGER, SOFTWARE ENGINEERING",Y,4.103154e+08,2013.0,"MOUNTAIN VIEW, CALIFORNIA",-122.083851,37.386052
2796071,2796071,2796072,WITHDRAWN,ICAP CORPORATES LLC,Financial Managers,"MANAGING DIRECTOR, EQUITY DERIVATIVES",Y,4.066379e+08,2011.0,"JERSEY CITY, NEW JERSEY",-74.077642,40.728158
1698325,1698325,1698326,DENIED,SAN LUIS VALLEY HEALTH,"Internists, General",INTERNIST,Y,3.893760e+08,2014.0,"ALAMOSA, COLORADO",NaN,NaN
2586866,2586866,2586867,DENIED,BAYSHORE GLOBAL MANAGEMENT LLC,Financial Managers,CHIEF INVESTMENT OFFICER,Y,3.783437e+08,2012.0,"LOS ALTOS, CALIFORNIA",-122.114130,37.385218
1780069,1780069,1780070,DENIED,HUNTSWORTH HEALTH NORTH AMERICA LLC,Financial Managers,"CHIEF FINANCIAL OFFICER, HUNTSWORTH HEALTH GLOBAL",Y,3.610381e+08,2014.0,"YARDLEY, PENNSYLVANIA",-74.845997,40.245664
2184108,2184108,2184109,WITHDRAWN,"MCLEOD REGIONAL MEDICAL CENTER OF THE PEE DEE,...","Physicians and Surgeons, All Other",ASSOCIATE MED. DIRECTOR & HOSPICE/PALLIATIVE CARE,Y,3.487515e+08,2013.0,"FLORENCE, SOUTH CAROLINA",-79.762563,34.195433
2190087,2190087,2190088,DENIED,"MCLEOD REGIONAL MEDICAL CENTER OF THE PEE DEE,...","Internists, General",ASSOCIATE MED. DIRECTOR & HOSPICE/PALLIATIVE CARE,Y,3.487515e+08,2013.0,"FLORENCE, SOUTH CAROLINA",-79.762563,34.195433
2191003,2191003,2191004,DENIED,"MCLEOD REGIONAL MEDICAL CENTER OF THE PEE DEE,...","Internists, General",ASSOCIATE MED. DIRECTOR & HOSPICE/PALLIATIVE CARE,Y,3.487515e+08,2013.0,"DARLINGTON, SOUTH CAROLINA",NaN,NaN
2685667,2685667,2685668,DENIED,"UROLOGY TODAY, LLC","Physicians and Surgeons, All Other","PHYSICIAN, UROLOGIST",Y,3.461120e+08,2011.0,"CRYSTAL CITY, MISSOURI",NaN,NaN
2522246,2522246,2522247,DENIED,"CLINIC BY THE SEA, LLC","Physicians and Surgeons, All Other",PHYSICIAN (GENERAL INVASIVE CARDIOLOGY/ELECTRO...,Y,3.461120e+08,2012.0,"MILLSBORO, DELAWARE",NaN,NaN
2921196,2921196,2921197,DENIED,AIR RESOURCES AMERICAS LLC,Petroleum Engineers,ELECTRICAL COMPLETIONS ENGINEER - LEVEL 4,Y,3.403587e+08,2011.0,"HOUSTON, TEXAS",-95.369803,29.760427
5579,5579,5580,DENIED,E AND D MEDIA INC.,MARKETING MANAGERS,"DIRECTOR, SOCIAL AND DIGITAL MEDIA",Y,3.291392e+08,2016.0,"SANTA MONICA, CALIFORNIA",-118.491191,34.019454
2831024,2831024,2831025,DENIED,KANSAS UNIVERSITY INTERNAL MEDICINE FOUNDATION,"Physicians and Surgeons, All Other","ASSISTANT PROFESSOR/HEMATOLOGY, BONE MARROW TR...",Y,3.213226e+08,2011.0,"KANSAS CITY, KANSAS",-94.627464,39.114053
2054920,2054920,2054921,DENIED,SEA MAR COMMUNITY HEALTH CENTER,"Internists, General",PHYSICIAN,Y,3.196544e+08,2013.0,"TACOMA, WASHINGTON",-122.444291,47.252877
633103,633103,633104,DENIED,U.S. DEPARTMENT OF VETERANS AFFAIRS,"PHYSICIANS AND SURGEONS, ALL OTHER",PHYSICIAN,Y,3.118045e+08,2016.0,"HOUSTON, TEXAS",-95.369803,29.760427
2989391,2989391,2989392,DENIED,"MOMENTUM-NA, INC.",Advertising and Promotions Managers,"VICE PRESIDENT, DIRECTOR OF STRATEGIC PLANNING",Y,3.077360e+08,2011.0,"NEW YORK, NEW YORK",-74.005941,40.712784
813742,813742,813743,DENIED,FRANCISCAN HEALTH SYSTEM,"PHYSICIANS AND SURGEONS, ALL OTHER",HOSPITALIST,Y,3.067418e+08,2015.0,"TACOMA, WASHINGTON",-122.444291,47.252877
1899911,1899911,1899912,DENIED,"DELL PRODUCTS, LP","Software Developers, Systems Software",NETWORK DEVELOPMENT SENIOR ENGINEER,Y,3.067418e+08,2013.0,"SAN JOSE, CALIFORNIA",-121.886329,37.338208

In [34]:
s.groupby(["company"])